resources:
  repositories:
    - repository: devops
      type: github
      name: MobisysGmbh/devops-templates
      endpoint: MobisysGmbH
      ref: refs/heads/release/v7

trigger: none
pr: none

extends:
  template: /yaml/kickstarter-templates/package-pipeline.yml@devops
  parameters:
    packageType: npm
    requireNvmrc: true
    targetFeed: mobisys-internal
    allowedPublishingBranches: refs/heads/release
    prePublishSteps:
      - task: CopyFiles@2
        inputs:
          Contents: 'mobisys-internal-cordova-plugin-camera-*.tgz'
          TargetFolder: 'publish'
          CleanTargetFolder: true
    linterSteps:
      - script: npm run lint
        displayName: Run Linter
    artifactsDirectoryToPublish: $(Build.SourcesDirectory)/publish
